import { stripIndent } from 'common-tags';
import { noPermissions, permissions } from '@/conf/configUtils';

export const eightBall = {
  settings: {
    aliases: ['8ball', 'eightball'],
    clientPermissions: permissions.SEND_MESSAGES,
    userPermissions: noPermissions,
  },
  details: {
    name: '8 Ball',
    content: "__Répond à toutes vos questions__, même les plus compliquées ! La légende raconte même qu'il y a déjà eu des bonnes réponses... :shushing_face:",
    usage: '8ball <votre question>',
    examples: ['8ball Dis moi mon beau miroir, suis-je le plus beau ?'],
  },
  messages: {
    promptStart: 'Je suis un bon devin, mais je ne peux pas deviner ta question. :confused: Entre-la en envoyant un message contenant seulement la question :',
    promptRetry: "Cette quetsion n'est pas valide. Entre-la en envoyant un message contenant seulement la question :",
    affirmative: [
      'Oui.',
      'Oui ! 🥳',
      "D'après moi, oui !",
      'Je le pense...',
      "C'est une chose sûre ! 😌",
      "C'est certain.",
      'Sans aucun doute ! 😁',
      'Il me semble...',
      'Pourquoi demander ? La réponse parait évidente ! Oui !',
      "ET C'EST UN OUI !",
      'Affirmatif, chef.',
      'Positif.',
      'BIEN ÉVIDEMMENT',
      'La réponse tient en un mot : oui.',
      'O U I',
      "C'est exact.",
      'Yep',
      'O̰̔͞u̝ͦ̕i̷̲̓',
      "C'est ca.",
      "Mais sources contradictoires m'affirment avec certitude que la réponse est positive. Bravo !",
      ':oui:',
    ],
    negative: [
        'Non.',
        'MDR NON',
        "C'est un non.",
        'Mes sources me confirment que non. 🙂',
        "C'est mieux que tu ne sois pas au courant... 😏",
        'Bien sur que non ! 😱',
        'Je ne suis pas sûr de comprendre...\nDans le doute, je vais dire non. 😅',
        'Question très compliquée...\nMais je dirai non. 😶',
        "Ou... Non ! C'est Non !",
        'Bien sur que non...',
        'Négatif.',
        'Je répondrai par la négation. Rah chui trop fort à ni-oui ni-non !\nTu ne me battras jamais. 😉',
        'Sûrement pas.',
        "Qui pourrait dire que c'est vrai ? C'est évidemment faux.",
        'N͔͑́o̧̰̔n̫̐͜',
        ':non:',
        'N O N',
        'Nopeee.',
        "Mercure est alignée avec Jupiter par Thor, donc selon le théorème d'Einstein et mon interprétation infaillible, la réponse est non.",
        'La réponse tient en seulement 3 lettres, dont 2 sont des "n" et celle du milieu est un "o". *(Ca ne rapporte pas beaucoup de point au scrabble.)*',
        'NoooooN',
    ],
  },
};

export const idea = {
  settings: {
    aliases: ['idea', 'idée', 'idee'],
    clientPermissions: permissions.SEND_MESSAGES,
    userPermissions: noPermissions,
  },
  details: {
    name: 'Idée',
    content: "Permet d'envoyer une __idée de script__ aléatoire à réaliser parmi celles dans le salon des idées.",
    usage: 'idée',
    examples: ['idea', 'idée'],
  },
  messages: {
    noIdeaFound: "Je n'ai trouvé aucune idée dans le salon !",
    ideaTitle: 'Idée de {name} :',
  },
};

export const joke = {
  settings: {
    aliases: ['joke', 'blague'],
    clientPermissions: permissions.SEND_MESSAGES,
    userPermissions: noPermissions,
  },
  details: {
    name: 'Blague',
    content: '__Envoie une blague__ aléatoirement, généralement drôle mais pas forcément.',
    usage: 'joke',
    examples: ['joke', 'blague'],
  },
  messages: {
    jokes: [
      'Un mec rentre dans un café.;Et plouf !',
      'Pourquoi les crocos sont en prison ?;Car les crocos dealent !',
      'Quelle mamie fait peur aux voleurs ?;Mamie Traillette !',
      "Quel est l'aliment le plus hilarant ?;Le riz !",
      'Pourquoi est-ce que le lapin est bleu ?;Parce qu’on lapin !',
      "D'où viennent les gens les plus dangereux ?;D’Angers !",
      'Comment est-ce que les abeilles communiquent entre elles ?;Par e-miel !',
      "Quel est l'arbre préféré des chômeurs ?;Le bouleau !",
      'Pourquoi est-ce que les moutons aiment le chewing-gum?;Parce que c’est bon pour la laine !',
      "Que dit une noisette quand elle tombe à l'eau ?;« Je me noix ! »",
      'Quel fruit est assez fort pour couper des arbres?;Le ci-tron',
      'Quel est le jambon que tout le monde déteste ?;Le sale ami !',
      "C'est l'histoire d'un papier qui tombe à l'eau.;Il crie « Au secours, j'ai pas pied ! »",
      'Que fait une fraise sur un cheval ?;Tagada Tagada !',
      'Tu connais la blague de la chaise ?;Elle est tellement longue !',
      "Tu connais l'histoire de la chaise ?;Elle est pliante !",
      'Comment appelle-t-on une catapulte à salade ?;Un lance-roquette !',
      'Comment appelle-t-on une bagarre entre une carotte et un petits pois ?;Un bon duel !',
      "Tu connais l'histoire du lit vertical ?;Elle est à dormir debout !",
      'Tu veux une blague à deux balles ?;Pan ! Pan !',
      "C'est l'histoire d'un Schtroumpfs qui court, qui court... Et il tombe.;Il s'est fait un bleu !",
      "Tu connais la blague du p'tit déj' ?;Pas de bol !",
      "Tu connais la blague de l'armoire ?;Elle est pas commode !",
      "Quel super héros donne le plus vite l'heure ?;Speed heure man !",
      'La vitamine C ne dira rien.;Mais elle le sais !',
      'Que veux dire « I don’t know » ?;« Je sais pas »',
      "Quelle est la femelle du hamster ?;L'Amsterdam !",
      'Que dit un oignon quand il se cogne ?;Aïe !',
      'Quel est le comble pour un marin ?;Avoir le nez qui coule !',
      'Quel est le sport le plus silencieux ?;Le para-chuuuut !',
      "Pourquoi ne faut-il jamais raconter d'histoires drôles à un ballon ?;Parce qu'il pourrait éclater (de rire) !",
      "Quel est l'animal le plus à la mode ?;La taupe modèle !",
      'Comment appelle t-on une fleur qui prend sa graine à moitié ?;Une migraine !',
      "J'ai fait une blague au magasin;Mais elle a pas supermarché !",
      'Pourquoi est-ce si difficile de conduire dans le Nord ?;Parce que les voitures arrêtent pas de caler !',
      "Qu'est-ce qu'un tennisman adore faire ?;Rendre des services !",
      "Pourquoi est-ce que les livres ont-ils toujours chaud ?;Parce qu'ils ont une couverture !",
      "Que se passe-t-il quand 2 poissons s'énervent ?;Le thon monte !",
      "Que dit une imprimante dans l'eau ?;J'ai papier !",
      "Pourquoi est-ce que les bières sont toujours stressées ?;Parce qu'elles ont la pression !",
      "Pourquoi est-ce que les éoliennes n'ont pas de copain ?;Parce qu’elles se prennent toujours des vents !",
      "Qu'est ce qu'un cadeau qui s'en va ?;Une surprise party !",
      "Comment savoir qu'un rat est content ?;Il souris !",
      'Que fait un geek quand il a peur ?;Il URL !',
      "Qu'est-ce qui est pire que le vent ?;Un vampire !",
      'Que dit une mère à son fils geek quand le dîner est servi ?;Alt Tab !',
      'Quelle est la meilleure heure pour écouter de la musique ?;10h !',
      'Que fait un geek quand il descend du métro ?;Il libère la RAM !',
      "Quel est l'animal le plus connecté ?;Le porc USB !",
      'Que fait un jardinier quand il ment ?;Il raconte des salades !',
      'Quel est le crustacé le plus léger de la mer ?;La palourde !',
      'Quel est le comble pour un maître nageur ?;Avoir le nez qui coule !',
      "Qu'est-ce qu'un Cheval de Mer qui a des douleurs musculaires ?;Un hippocrampe !",
      'Quelle est la monnaie des poissons ?;Les sous-marins !',
      'Que dit un donuts à la plage ?;Je vais me beignet !',
      "Pourquoi peut-on dire que le chef d'établissement d'un lycée est un sniper ?;Parce que c'est un proviseur !",
      "Pourquoi tu fais 20 fois le tour du lycée sans t'arrêter ?;Parce que je poursuis mes études !",
      "Tu connais l'histoire du lit vertical ?;C'est une histoire à dormir debout !",
      "Que disent deux planètes dans un parc d'attraction ?;Oulah sa turne !",
      "Quelle est le comble pour une pomme de terre ?;Qu'elle s'effrite !",
      "Comment appelle-t-on un chien qui s'y connait en médecine ?;Un dogteur !",
      'Quel est le sport le plus silencieux ?;Le parachuuuute !',
      'Comment appelle-t-on un boomerang qui ne revient pas ?;Un bout de bois !',
      'Si une voiture roule à 70 km/h dans un virage à droite, quelle roue va la moins vite ?;La roue de secours !',
      'Que mange-t-on à la naissance ?;Du riz cantonais !',
      "Que dit-on à un poisson mal poli ?;Baisse d'un ton !",
      'Que fait un vendeur de chaussure qui est curieux ?;Il semelle de tout !',
      "Pourquoi il n'y a pas de ballon sur le plateau de Questions pour un Champion ?;Parce que Julien Lepers !",
      'Que fait un matheux quand il va au toilette ?;Il fait pipi !',
      'Comment un aspirateur peut-il mourir ?;En mordant la poussière !',
      'Où dansent les biscottes ?;À la biscottèque !',
      'Où se cachent les canards ?;Dans les coins-coins !',
      'Pourquoi le père noël a-t-il une barbe blanche ?;Pour ne pas le confondre avec le petit chaperon rouge !',
      "Comment sortir d'un casino avec une petite fortune ?;En y entrant avec une grosse fortnue !",
      "Comment faire pour qu'un fromage ne coule pas ?;Il faut lui apprendre à nager !",
      "Qu'est-ce qui est vert et qui a la chair de poule ?;Hulk quand il a froid.",
      "Pourquoi l'échalote dit allo ?;Parce que l'iphone ! (ail phone)",
      "Qu'est-ce qui est blanc, noir, jaune, blanc et noir ?;Deux zèbres qui se battent pour une banane.",
      'Pourquoi certaines personnes jettent-elles leur ordinateur a la mer ?;Pour surfer sur le net.',
      "Que disent deux bonshommes de neige qui se rencontrent ?;Tu ne trouves pas que ça sent la carotte aujourd'hui ?",
      "Qu'est ce qu'un taureau avec un string ?;Une vache folle.",
      "Quelle est la plus basse note de musique ?;Fa, parce qu'elle est sous le sol.",
      'Pourquoi les éléphants mettent-ils des lunettes noires ?;Pour passer inaperçus.',
      'Comment appelle-t-on une patate un soir de pleine lune ?;Une patate-garou !',
      "Comment appelle t'on un chat qui éteint les feux ?;Un chat peur pompier.",
    ],
  },
};

export const latex = {
  settings: {
    aliases: ['latex'],
    clientPermissions: permissions.SEND_MESSAGES,
    userPermissions: noPermissions,
  },
  details: {
    name: 'Latex',
    content: 'Permet de transformer une série de symboles pas belle du tout en une __merveilleuse équation__ toute jolie, grâce au moteur mathématique LaTeX.',
    usage: 'latex <equation>',
    examples: ['latex x = \\frac{4}{5}+\\pi\\Omega\\int_{2\\pi}^{\\infty}{5\\left\\(\\\\frac{\\tau+3}{2}\\right\\)d\\omega}'],
  },
  messages: {
    startPrompt: 'Ajoute une équation à formater :',
    retryPrompt: 'Équation invalide. Ré-entre-la :',
  },
};

export const poll = {
  settings: {
    aliases: ['poll', 'sondage'],
    clientPermissions: permissions.SEND_MESSAGES | permissions.MANAGE_MESSAGES | permissions.ADD_REACTIONS,
    userPermissions: noPermissions,
  },
  details: {
    name: 'Sondage',
    content: 'Permet de __lancer un sondage__ temporaire par lequel on peut répondre par Oui / Non ou par une réponse personnalisée. Ajoute le drapeau `-a` pour indique que le sondage sera anonyme, ~~ou le drapeau `-m` pour autoriser les réponses multiples~~ *(soon)*.',
    usage: 'poll <durée> [-a] [-m] "<sondage>" ["réponse 1"] ["réponse 2"] [...]',
    examples: ['poll 10m "votre sondage" "réponse 1" "réponse 2" "réponse 3" "réponse 4"', 'vote 10m Votre sondage ou on peut répondre uniquement par Oui et Non', 'sondage 10m "votre sondage" -a -m "réponse 1" "réponse 2"'],
  },
  messages: {
    promptStartDuration: 'Il faut ajouter une durée (en anglais ou en francais). Tu peux par exemple entrer `1s` pour 1 seconde, `1min` pour 1 minute et `1j` pour 1 jour. Tu peux également combiner ces durées ensemble : `5j15min300s` est par exemple une durée valide. Entre-la en envoyant un message contenant seulement la durée :',
    promptRetryDuration: "Cette durée n'est pas valide. Tu peux par exemple entrer `1s` pour 1 seconde, `1min` pour 1 minute et `1j` pour 1 jour. Tu peux également combiner ces durées ensemble : `5j15min300s` est par exemple une durée valide. Entre-la en envoyant un message contenant seulement la durée :",
    promptStartContent: "Ajoute un sondage à effectuer ! Si tu souhaites qu'on ne puisse répondre que par oui ou non, alors tu peux simplement marquer ta question. Sinon, écrit ta question entre guillements (`\"`), puis écrit les réponses possibles entre guillement également (`\"`). Par exemple, tu peux faire `.poll 10min \"Voici ma question\" \"Réponse 1\" \"Réponse 2\" \"Réponse 3\"`.",
    promptRetryContent: "Ce sondage n'est pas valide. Entre-le en envoyant un message contenant seulement ta question (et tes réponses si c'est un sondage à réponse multiples) :",
    notEnoughAnswers: "Tu n'as entré qu'une seule réponse. Ré-exécute la commande avec plusieurs réponses !",
    tooManyAnswers: 'Tu as entré trop de réponses. Ré-exécute la commande avec au maximum 18 réponses.',
    answersDisplayYesno: stripIndent`
      :white_check_mark: Oui
      :x: Non
    `,
    answersDisplayCustom: '{reaction} {answer}\n',
    informationAnonymous: 'Ce sondage est anonyme.',
    informationMultiple: 'Plusieurs réponses sont possibles.',
    embed: {
      author: 'Vote de {message.member.displayName}',
      question: 'Question',
      answers: 'Réponses possibles',
      duration: 'Durée',
      durationContent: 'Ce vote dure {formattedDuration} (fini {formattedEnd})',
    },
  },
};
