name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Node ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm ci

      - name: Check TypeScript types
        run: npm run typecheck

      - name: Build project
        run: npm run build
